### ISSUE TITLE
Questionable fork?

### ISSUE THREAD

**Issue by klvs** [doitles/CS101#1]
Hi Luke, 

I noticed you forked my CS101 repo which brought to my attention that it wasn't private.

I'm slightly concerned about the potential similarity in our work.

Hopefully this isn't an issue. I don't mean to accuse you of anything. Perhaps I'm mistaken; I haven't looked into this thoroughly yet. Maybe you can clear up any confusion here? I noticed some of the commit timestamps are after the deadline for the submission.

Best,
Alex

<img width="1404" alt="ermfork" src="https://cloud.githubusercontent.com/assets/5811023/13728306/094340cc-e8d1-11e5-8d27-76869ddc32b5.png">

**Comment by doitles** [comment]
Hey Alex,
I found this when I was looking what to do with MySet. I think I accidently forked, but I don't think there's anything to worry about since I just left MySet pretty much the way the teacher had it with some minor changes.

Best,
Luke

**Comment by klvs** [comment]
Okay, thanks for responding. I was just concerned that you had possibly just forked it and change some variable names. It doesn't look to be the case after comparing code more thoroughly. Just had to check to make sure. I'm thinking we should probably make these repos private in the future; looking at the traffic stats I've got a bunch of unique hits from google, github and even facebook.

Anyway, thanks again for getting back to me.
